### ISSUE TITLE
Recent Transactions - not updating

### ISSUE THREAD

**Issue by pvk444** [spectrecoin/spectre#10]
Since about 4 days the "Recent Transactions"-tab in the Windows client is not updating any more. It is staking and the total balance is adjusted accordingly. Only the Transaction tab is not updating. 
Restarting the app, however, updates the Recent Transaction tab once, but only once and leaves it then again stale. 

This used to work previously, and since I have not made any changes to my system, it's not clear where the problem stems from. 

This is not a critical issue, as otherwise everything seems to work as expected.

**Comment by jbg** [comment]
This issue should be resolved as of v1.3.1. Please download the latest release (now v1.3.2) and reopen if it still occurs.
