### ISSUE TITLE
How to load the backup.dat file

### ISSUE THREAD

**Issue by Oliver7580** [spectrecoin/spectre#14]
Hello
How do i use the backup.dat for wallet restoring?

**Comment by jbg** [comment]
If `backup.dat` is simply a backup copy of `wallet.dat` from a previous SpectreCoin wallet, just make sure the Spectre wallet is not running, and then copy it into your data directory (on Linux, it's `$HOME/.spectrecoin`, on Windows it's a folder called SpectreCoin inside your Windows profile application data directory). Make sure it is named `wallet.dat`. Then launch the wallet again.

**Comment by Oliver7580** [comment]
Thank you for your reply,i am on Windows 10,but i can't find the folder,that you mean.i only found the normal folder where the .exe is in.

**Comment by Oliver7580** [comment]
Hello I still have not found the right folder :(

**Comment by bitcoinx2** [comment]
Please come to Slack and let me help you there, Oliver. https://slack.spectreproject.io

**Comment by jbg** [comment]
Closing because, as @bitcoinx2 points out, this is not a bug but a support request. Please join slack and ask for help :)
