### ISSUE TITLE
Docker Please

### ISSUE THREAD

**Issue by mbalance** [spectrecoin/spectre#15]
Please make a docker so I can run this without all those dependencies on my server :)

**Comment by jbg** [comment]
Pull requests are gladly accepted, but a Docker image is not currently on the roadmap. Note that almost any base Linux install already includes OpenSSL, libevent and Boost, and you don't need Qt if you don't want to build the GUI. So there aren't really any dependencies to install.

When 1.4 is released it will include .deb and AUR packages so if you run a Debian-based distribution or Arch, you can just install the binary package.
