### ISSUE TITLE
Default nodes are outdated

### ISSUE THREAD

**Issue by bitcoinx2** [spectrecoin/spectre#21]
When starting the wallet for the first time on Linux, there will be zero connections until further nodes from https://chainz.cryptoid.info/xspec/#!network have been added. The default nodes should be up to date, so that no manual configuration is necessary.

A detailed tutorial for adding nodes manually can be found here: https://github.com/bitcoinx2/spectre/wiki/FAQ#7-i-have-zero-connections

**Comment by elefthei** [comment]
Would this work? https://github.com/spectrecoin/spectre/pull/24

**Comment by jbg** [comment]
Fixed in b4eec465cb31efcf71b7d8c858c127cf5394f80d
