### ISSUE TITLE
On Mac "Wallet is syncing" for 2+ hours

### ISSUE THREAD

**Issue by moleculezz** [spectrecoin/spectre#27]
I don't know if it's syncing or if it's not doing anything. It doesn't seem to have a progress bar like I see from screenshots of windows users.

I tried to check the Activity Monitor, but it doesn't show anything in the Network tab for Spectre.

Can anyone tell me if it's working on Mac and if it's just slow to sync?

**Comment by bitcoinx2** [comment]
This is not a support forum, please head to Bitcointalk or Slack (channel #client_support) for user support. Your problem is related to this bug: https://github.com/spectrecoin/spectre/issues/21

**Comment by bitcoinx2** [comment]
Could you provide a screenshot? Also note that we have a #client_support channel on Slack. If you are reporting here, you should be sure that it's a bug.

**Comment by moleculezz** [comment]
Right.. sorry, will use that instead next time.

Here is the screenshot. I've left it on a whole night, no change or any progress.
<img width="1297" alt="spectre_snapshot" src="https://user-images.githubusercontent.com/118499/33833601-89bdeac8-de56-11e7-9bc9-c971b1ab4844.png">

**Comment by bitcoinx2** [comment]
Right, this is bug No. 21: https://github.com/spectrecoin/spectre/issues/21

The solution is to add nodes: https://github.com/bitcoinx2/spectre/wiki/FAQ#7-i-have-zero-connections

**Comment by moleculezz** [comment]
Great.. it has peers now. Thanks.
