### ISSUE TITLE
Libboost

### ISSUE THREAD

**Issue by falsificado** [spectrecoin/spectre#4]
The unix binary is asking for an old version of libboost, and throws an error at start:

`error while loading shared libraries: libminiupnpc.so.8: cannot open shared object file: No such file or directory`

Using Debian Stretch, running spectre v1.1.0.0b

**Comment by jbg** [comment]
This issue should be resolved as of v1.3.0. Please download the latest release (now v1.3.2) and reopen if it still occurs.
