### ISSUE TITLE
Balance is zero on startup

### ISSUE THREAD

**Issue by bitcoinx2** [spectrecoin/spectre#5]
Sometimes when starting the wallet, the balance will show up as zero. There is no (known) pattern for this happening. My system is Debian x86, I don't know whether Windows users are affected. This problem has been reported multiple times by different people.

Symptoms: Total balance is shown as 0.00 XSPEC, no transactions are shown, under "Balances" all 6 kinds of balance (public, private, reserved, stake, unconfirmed, immature) are shown as zero. When going to "Wallets"->"Receive", there are NO receive addresses listed at all.

Possible solutions seem to be, restarting the wallet multiple times (doesn't fix it reliably), rebooting the system, recompiling the wallet or setting up the wallet again from scratch and copying wallet.dat. Sometimes the problem goes away simply by waiting a few minutes, and everything will magically show up.

**Comment by jbg** [comment]
Can you confirm whether this still occurs on the latest released version?

**Comment by bitcoinx2** [comment]
I wasn't able to reproduce it by restarting my (previously running) wallet, but that doesn't mean it's never going to happen again. This wasn't always reproducible before, either.

**Comment by jbg** [comment]
Thanks for the response. I have fixed several bugs related to the UI not updating correctly in the upcoming release, so please let me know if it happens again, especially after you upgrade to the next release (should be out in the next few days).

**Comment by jbg** [comment]
This issue should be resolved as of v1.3.1. Please download the latest release (now v1.3.2) and reopen if it still occurs.
