### ISSUE TITLE
Error installing specter wallet - Windows 7

### ISSUE THREAD

**Issue by hectorrojas150** [spectrecoin/spectre#6]
I have an error when I want to install the wallet on windows 7.
The error says: The procedure entry point _create_locale is not found in the dynamic link library msvcrt.dll
Can someone help me please?

**Comment by spectrecoin** [comment]
Noted. We are currently working on updates for several Windows version.

**Comment by jbg** [comment]
This issue should be resolved as of v1.3.0. Please download the latest release (now v1.3.2) and reopen if it still occurs.
