### ISSUE TITLE
Balance shows zero and no transactions

### ISSUE THREAD

**Issue by drfabricius** [spectrecoin/spectre#9]
My issue is the same as one of the previous issues called "Balance is Zero on Startup".  I have the newest version 64 bit wallet (1.2.0.0) with addresses working well and synch'ing fine.  I needed to setup a x86 windows 7 PC to stake 24/7.  The only version available I could find was 1.1.0.0b .  I installed it, and replaced the wallet file manually since I really couldn't import it.
When I first opened this new x86 wallet, the transaction history showed up but the balance was 0.00 XSPEC. 
![20170620_091905](https://user-images.githubusercontent.com/29573071/27333031-cb564fa6-559a-11e7-978f-c79fcd0eaf8f.jpg)
 I Waited untill it fully synched and the balance is still zero.  However, it says "staking with xxx weight", which is by the way the correct ammount I have in the wallet (even though the total balance is zero). 
![20170620_091914](https://user-images.githubusercontent.com/29573071/27333057-e5226b72-559a-11e7-8be5-81bd73831789.jpg)
There is no receiving address. 
![20170620_092224](https://user-images.githubusercontent.com/29573071/27333067-f03d044a-559a-11e7-8fe0-2542c3d58ee7.jpg)
 When I close the wallet, it crashes hard with a lot of popping ups.
![20170620_093006](https://user-images.githubusercontent.com/29573071/27333137-3f7a31cc-559b-11e7-8f3e-6da00b1397d4.jpg)
![20170620_093020](https://user-images.githubusercontent.com/29573071/27333144-47b34ef0-559b-11e7-9d51-7cd1d65cfbbd.jpg)

When I open the wallet anytime after the first time, the recent transactions disapear  and every issue persists.

**Comment by jbg** [comment]
Thanks for the report. I looked into this last night, and this is a known issue in 1.1.0.0b. It is already fixed in 1.2.0.0, but you unfortunately can't run this version as there was no 32-bit version of it released.

I will be releasing 32-bit builds of 1.3.0.0 when it's ready, so you will be able to update and this issue will go away.

**Comment by jbg** [comment]
This issue should be resolved as of v1.3.1. Please download the latest release (now v1.3.2) and reopen if it still occurs.
